const mongoose=require('mongoose');
const Schema=mongoose.Schema

const InsuranceSchema=new Schema({
    title:{
        type:String,  
    },
    owner:{
        type:String
    },
    url:{
        type:String
    },
    address:{
        type:String
    },
    email:{
        type:String
    },
    number:{
        type:String
    },
    companyRegNumber:{
        type:String
    },
    comprehensive:{
        type:Boolean
    },
    image: {
        public_id: {
            type:String
        },
        url: {
            type:String
        }
    },
    Tier:{
        type:Boolean
    },
    Rapid:{
        type:Boolean
    },
    Virtual:{
        type:Boolean
    },
    Extensive:{
        type:Boolean
    },
    NoCbonus:{
        type:Boolean
    },
    freeLife:{
        type:Boolean
    },
    OnSite:{
        type:Boolean
    },
    DirectSettle:{
        type:Boolean
    },
    Extentions:{
        type:Boolean
    },
    FuneralExpense:{
        type:Boolean
    },
    AccInjury:{
        type:Boolean
    },
    Air:{
        type:Boolean
    },
    WildScreen:{
        type:Boolean
    },
    Call:{
        type:Boolean
    },
    AlterTrans:{
        type:Boolean
    },
    AlterVehicle:{
        type:Boolean
    },
    ThirdParty:{
        type:Boolean
    },
    Surgery:{
        type:Boolean
    },
    DamagedKey:{
        type:Boolean
    },
    Freesound:{
        type:Boolean
    },
    BackTo:{
        type:Boolean
    },
    OptionsOf:{
        type:Boolean
    },
    Baby:{
        type:Boolean
    },
    Agift:{
        type:Boolean
    },
    FreePersonal:{
        type:Boolean
    },
    Other:{
        type:Boolean
    },
    Online:{
        type:Boolean
    },
    FreeTowing:{
        type:Boolean
    },
    DoorStep:{
        type:Boolean
    }

})

const Insurance=mongoose.model('Insurance',InsuranceSchema)
module.exports=Insurance